apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    package: core
  name: hapi-fhir-server-matchbox
  namespace: default
spec:
  selector:
    matchLabels:
      component: hapi-fhir-server
  template:
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "1"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-postgres: postgres-db/data/fhir
        vault.hashicorp.com/agent-inject-template-postgres: |
          {{- with secret "postgres-db/data/fhir" -}}
            export POSTGRES_DB={{ .Data.data.POSTGRES_DB }}
            export SPRING_DATASOURCE_USERNAME={{ .Data.data.POSTGRES_USER }}
            export SPRING_DATASOURCE_PASSWORD={{ .Data.data.POSTGRES_PASSWORD }}
            export SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_FHIR_SERVICE_HOST}:${POSTGRES_FHIR_SERVICE_PORT}/{{ .Data.data.POSTGRESQL_DATABASE }}
            {{- end -}}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: fhir-server
      creationTimestamp: null
      labels:
        component: hapi-fhir-server
    spec:
      containers:
      - args:
        - -c
        - . /vault/secrets/postgres && java -Xmx1G -Xshareclasses -Xquickstart -jar
          /app.jar -Dspring.config.additional-location=optional:file:/config/application.yaml,optional:file:application.yaml
        command:
        - /bin/sh
        env:
        - name: SPRING_DATASOURCE_DRIVERCLASSNAME
          value: org.postgresql.Driver
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: HAPI_FHIR_ALLOW_EXTERNAL_REFERENCES
          value: "true"
        image: eu.gcr.io/fhir-ch/matchbox:v140
        imagePullPolicy: IfNotPresent
        name: hapi-fhir-server
      serviceAccount: hapi-fhir-server
      serviceAccountName: hapi-fhir-server