kind: Service
apiVersion: v1
metadata:
  name: hapi-fhir-server-matchbox
  namespace: default
  labels:
    app: hapi-fhir-server-matchbox
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hapi-fhir-server-matchbox
  type: ClusterIP
