apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-fhir
  name: postgres-fhir
  namespace: default
spec:
  ports:
  - nodePort: 31790
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-fhir
  type: ClusterIP