apiVersion: v1
kind: Service
metadata:
  labels:
    app: hapi-fhir-server
  name: hapi-fhir-server
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hapi-fhir-server
  type: ClusterIP