apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-admin-ui
  name: postgres-admin-ui
  namespace: default
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: postgres-admin-ui
  type: ClusterIP