apiVersion: v1
kind: Service
metadata:
  labels:
    app: openhim-console
  name: openhim-console
  namespace: default
spec:
  ports:
  - name: "9000"
    port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    app: openhim-console
  type: ClusterIP