apiVersion: v1
kind: Service
metadata:
  name: postgres-kc
  namespace: default
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-kc
  type: ClusterIP