apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: openhim-core
    name: openhim-core
    namespace: default
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: "5000"
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: "5001"
      port: 5001
      protocol: TCP
      targetPort: 5001
    - name: "5050"
      port: 5050
      protocol: TCP
      targetPort: 5050
    - name: "5051"
      port: 5051
      protocol: TCP
      targetPort: 5051
    - name: "5052"
      port: 5052
      protocol: TCP
      targetPort: 5052
    - name: "7788"
      port: 7788
      protocol: TCP
      targetPort: 7788
    selector:
      app: openhim-core
    type: ClusterIP