name: ci-main
on:
  push:
    branches:
    - master
    paths:
    - components/trustregistry/**
jobs:
  build:
    runs-on: ubuntu-20.04
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: version
      run: |-
        APP_SHA=$(git rev-parse --short ${GITHUB_SHA})
        APP_LATEST_REV=$(git rev-list --tags --max-count=1)
        APP_LATEST_TAG=$(git describe --tags ${APP_LATEST_REV} 2> /dev/null || echo 0.0.0)
        APP_VERSION=${APP_LATEST_TAG}-${APP_SHA};
    - name: docker
      run: |-
        echo "${APP_PACKAGES_PASSWORD}" | docker login "${APP_PACKAGES_URL}" \
        --username "${APP_PACKAGES_USERNAME}" \
        --password-stdin
        docker build ./components/trustregistry \
        --tag "${APP_PACKAGES_URL}:${APP_VERSION}"
        docker push "${APP_PACKAGES_URL}:${APP_VERSION}"
      env:
        APP_PACKAGES_URL: docker.pkg.github.com/${{ github.repository }}/tpri/components/trustregistry
        APP_PACKAGES_USERNAME: ${{ github.actor }}
        APP_PACKAGES_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
