apiVersion: v1
kind: Service
metadata:
  name: svc-transactions
  namespace: default
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: svc-transactions
  type: ClusterIP
